apiVersion: v1
kind: Service
metadata:
  name: mdrepo-frontend-svc
  namespace: mudry-ns
spec:
  type: ClusterIP
  selector:
    app: mdrepo-frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
